
logger: "console"

log: "core"

warnings: 1

show_errors: 0

log: core

plugins:
  DBIC:
    billing:
      schema_class: Local::Schema
      dsn:  "dbi:Pg:dbname=local;host=db;port=5432"
      user: "local-db"
      password: "local-test-password"