version: "3"
services:
  app:
    container_name: 'dancer2-sample'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app/
      - ./t:/app/t
    ports:
      - 5000:3000

  vault:
    image: hashicorp/vault:latest
    container_name: vault_dev
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root-token" 
    restart: always

    networks:
      - docker_tucows-billing-network

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    networks:
      - docker_tucows-billing-network
  
  redis:
    image: redis:7.0.11
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - docker_tucows-billing-network

volumes:
  db:
    driver: local

networks:
  docker_tucows-billing-network:
    external: true