version: "3"
services:
  app:
    container_name: 'dancer2-sample'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app/
      - ./t:/app/t
    ports:
      - 5000:3000

  vault:
    image: hashicorp/vault:latest
    container_name: vault_dev
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root-token" 
    restart: always