name: Perl Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Perl
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: '5.38'

    - name: Cache Perl and Carton dependencies
      id: cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cpanm
          ./local
        key: ${{ runner.os }}-perl-carton-${{ hashFiles('cpanfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-perl-carton-

    - name: Install dependencies
      run: cpanm --quiet --installdeps .

    - name: Install Carton dependencies
      run: carton install --cached

    - name: Run tests
      run: prove -lvr t

    - name: Save Perl and Carton dependencies cache
      if: steps.cache.outputs.cache-hit == 'false'
      run: |
        cpanm --quiet --snapshot
        carton bundle
